CREATE TABLE proxy_stops (
    region_id TEXT,
    stop_name TEXT
);

-- via "20210817 Gemeinden Bahnhof MARA.xlsx" / "20210817 Gemeinden Bahnhof MARA_jok.ods"
-- special cases where the direction of travel leads to another station have to be handled separatedly
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076070', 'Hagenow Land Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076063', 'Holthusen Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076006', 'Inselstadt Malchow');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076007', 'Crivitz Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076004', 'Hagenow Land Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076005', 'Schwerin Hauptbahnhof');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076008', 'Hagenow Land Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076009', 'Boizenburg Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076029', 'Crivitz Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076010', 'Boizenburg Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076013', 'Hagenow Land Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076014', 'Boizenburg Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076011', 'Blankenberg');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076012', 'Neustadt-Gl. Wabeler Str.');  -- Neustadt-Glewe, via Meeting 20210826
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076002', 'Hagenow Land Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076003', 'Grabow Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076001', 'Ludwigslust Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076026', 'Blankenberg');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076027', 'Ludwigslust Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076032', 'Parchim Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076030', 'Brahlstorf Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076035', 'Parchim Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076036', 'Schwerin Hauptbahnhof');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076033', 'Ventschow Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076034', 'Ludwigslust Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076017', 'Pritzier Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076018', 'Ludwigslust Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076020', 'Blankenberg');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076015', 'Parchim Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076016', 'Brahlstorf Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076019', 'Hagenow Land Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076021', 'Grabow Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076024', 'Ventschow Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076025', 'Crivitz Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076023', 'Crivitz Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076048', 'Parchim Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076049', 'Ludwigslust Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076053', 'Ludwigslust Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076054', 'Boizenburg Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076051', 'Parchim Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076057', 'Hagenow Land Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076058', 'Ludwigslust Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076055', 'Boizenburg Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076056', 'Parchim Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076050', 'Grabow Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076039', 'Boizenburg Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076037', 'Ludwigslust Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076038', 'Parchim Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076043', 'Parchim Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076040', 'Parchim Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076041', 'Hagenow Land Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076046', 'Ludwigslust Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076044', 'Schwerin Hauptbahnhof');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076075', 'Parchim Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076076', 'Grabow Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076073', 'Hagenow Land Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076079', 'Hagenow Land Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076077', 'Parchim Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076078', 'Blankenberg');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076071', 'Schwerin Hauptbahnhof');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076072', 'Grabow Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076068', 'Parchim Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076069', 'Ludwigslust Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076064', 'Hagenow Land Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076065', 'Hagenow Land Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076062', 'Blankenberg');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076067', 'Ludwigslust Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076060', 'Hagenow Land Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076119', 'Hagenow Land Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076126', 'Parchim Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076129', 'Parchim Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076130', 'Schwerin Süd');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076131', 'Hagenow Land Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076134', 'Ludwigslust Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076135', 'Ludwigslust Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076128', 'Blankenberg');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076132', 'Parchim Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076125', 'Parchim Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076133', 'Crivitz Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076165', 'Parchim Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076118', 'Rastow Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076117', 'Schwerin Hauptbahnhof');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076120', 'Parchim Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076116', 'Pritzier Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076114', 'Inselstadt Malchow');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076115', 'Grabow Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076122', 'Schwanheide');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076123', 'Hagenow Land Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076121', 'Schwerin Süd');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076143', 'Pritzier Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076147', 'Schwerin Süd');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076152', 'Hagenow Land Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076148', 'Blankenberg');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076153', 'Hagenow Land Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076154', 'Schwerin Hauptbahnhof');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076151', 'Parchim Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076155', 'Blankenberg');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076156', 'Ludwigslust Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076138', 'Boizenburg Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076139', 'Hagenow Land Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076136', 'Boizenburg Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076141', 'Rastow Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076142', 'Brahlstorf Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076137', 'Parchim Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076146', 'Ludwigslust Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076140', 'Crivitz Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076145', 'Hagenow Land Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076158', 'Crivitz Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076159', 'Hagenow Land Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076167', 'Blankenberg');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076163', 'Schwerin Süd');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076161', 'Grabow Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076164', 'Parchim Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076162', 'Parchim Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076166', 'Meyenburg Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076160', 'Parchim Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076105', 'Neustadt-Gl. Wabeler Str.');  -- Neustadt-Glewe, via Meeting 20210826
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076106', 'Boizenburg Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076103', 'Ludwigslust Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076109', 'Parchim Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076104', 'Parchim Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076108', 'Parchim Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076112', 'Schwerin Hauptbahnhof');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076113', 'Rastow Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076110', 'Hagenow Land Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076107', 'Schwerin Süd');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076111', 'Ludwigslust Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076101', 'Blankenberg');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076102', 'Boizenburg Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076100', 'Grabow Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076097', 'Grabow Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076095', 'Parchim Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076098', 'Grabow Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076096', 'Parchim Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076090', 'Ludwigslust Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076093', 'Ludwigslust Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076099', 'Hagenow Land Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076094', 'Ludwigslust Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076092', 'Boizenburg Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076086', 'Ludwigslust Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076087', 'Ludwigslust Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076084', 'Ludwigslust Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076085', 'Ludwigslust Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076089', 'Parchim Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076088', 'Hagenow Land Bhf');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076082', 'Schwerin Hauptbahnhof');
INSERT INTO proxy_stops(region_id, stop_name) VALUES ('13076080', 'Schwerin Hauptbahnhof');

CREATE INDEX idx_proxy_stops_region_id ON proxy_stops(region_id);
CREATE INDEX idx_proxy_stops_stop_name ON proxy_stops(stop_name);
